### ISSUE TITLE
Template feedback

### ISSUE THREAD

**Issue by brody192** [Mys7erio/kali-railway#1]
Hello! This is a great template, I only have one suggestion.
Use [template variable functions](https://docs.railway.app/guides/create#template-variable-functions)
For the username: `${{secret(16, "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")}}`
For the password: `${{secret(32)}}`

**Comment by Mys7erio** [comment]
Hey, thanks a lot for the suggestion. I have looked into the template variable functionality and have successfully changed the template to use random credentials.

I will be closing the issue now. Thank you
